Models/Caption.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Caption
    {
        public string text { get; set; }
        public double confidence { get; set; }
    }
}

Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Category
    {
        public string name { get; set; }
        public double score { get; set; }
        public Detail detail { get; set; }
    }
}

Models/Color.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Color
    {
        public string dominantColorForeground { get; set; }
        public string dominantColorBackground { get; set; }
        public List<string> dominantColors { get; set; }
        public string accentColor { get; set; }
        public bool isBwImg { get; set; }
    }
}

Models/Description.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Description
    {
        public List<string> tags { get; set; }
        public List<Caption> captions { get; set; }
    }
}

Models/Detail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Detail
    {
        public List<object> celebrities { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace GABCognitiveServices.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ImageAnalysis.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class ImageAnalysis
    {
        public int Id { get; set; }
        public byte[] imageByte { get; set; }
    }
}

Models/ImageInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace GABCognitiveServices.Models
{
    public class ImageInfoViewModel
    {
        public List<Category> categories { get; set; }
        public Description description { get; set; }
        public Color color { get; set; }
        public string requestId { get; set; }
        public Metadata metadata { get; set; }
        public byte[] imageByte { get; set; } 
        public OpticalCharacterRecognition OCR { get; set; }
    }
}

Models/Line.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Line
    {
        public string boundingBox { get; set; }
        public List<Word> words { get; set; }
    }
}

Models/Metadata.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Metadata
    {
        public int height { get; set; }
        public int width { get; set; }
        public string format { get; set; }
    }
}

Models/OpticalCharacterRecognition.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class OpticalCharacterRecognition
    {
        public double textAngle { get; set; }
        public string language { get; set; }
        public string orientation { get; set; }
        public List<Region> regions { get; set; }
    }
}

Models/Region.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Region
    {
        public string boundingBox { get; set; }
        public List<Line> lines { get; set; }
    }
}

Models/VisualFeature.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class VisualFeature
    {
        public IFormFile upload { get; set; }
        public bool Categories { get; set; }
        public bool Tags { get; set; }
        public bool Description { get; set; }
        public bool Face { get; set; }
        public bool ImageType { get; set; }
        public bool Color { get; set; }
        public bool Adult { get; set; }

        public String visualFeaturesTags(VisualFeature vf)
        {
            String tags = "";
            foreach (PropertyInfo propertyInfo in vf.GetType().GetProperties())
            {
                if ((bool)propertyInfo.GetValue(vf))
                {
                    tags = tags + propertyInfo.Name;
                }               
            }
            return tags;
        }
    }
}

Models/Word.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GABCognitiveServices.Models
{
    public class Word
    {
        public string boundingBox { get; set; }
        public string text { get; set; }
    }
}

Controllers/CognitiveServicesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using GABCognitiveServices.BusinessLayer;
using GABCognitiveServices.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace GABCognitiveServices.Controllers
{
    public class CognitiveServicesController : Controller
    {
        IConfiguration _iconfiguration;

        public CognitiveServicesController(IConfiguration iconfiguration)
        {
            _iconfiguration = iconfiguration;
        }


        // GET: CognitiveServices/NovaAnalise
        public ActionResult NovaAnalise()
        {
            return View();
        }

        // POST: CognitiveServices/NovaAnalise
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NovaAnalise(IFormFile upload, String urlText)
        {
            if (upload != null)
            {
                try
                {
                    ImageInfoViewModel imageInfo;
                    imageInfo = await new VisionService(_iconfiguration).MakeAnalysisRequest(upload);                    
                    ViewBag.imageFile = "data:" + upload.ContentType + ";base64, " + Convert.ToBase64String(imageInfo.imageByte, 0, imageInfo.imageByte.Length);
                    imageInfo.imageByte = null;
                    String json = JsonConvert.SerializeObject(imageInfo, Formatting.Indented);
                    ViewBag.imageInfoStr = json;
                    return View();
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                try
                {
                    ImageInfoViewModel imageInfo;
                    imageInfo = await new VisionService(_iconfiguration).MakeAnalysisRequest(null, urlText);
                    String json = JsonConvert.SerializeObject(imageInfo, Formatting.Indented);
                    ViewBag.imageInfoStr = json;
                    ViewBag.imageFile = urlText;
                    return View();
                }
                catch
                {
                    return View();
                }
            }   
            
        }

        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GABCognitiveServices.Models;

namespace GABCognitiveServices.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CognitiveServices/NovaAnalise.cshtml
@model Microsoft.AspNetCore.Http.IFormFile

@{
    ViewData["Title"] = "NovaAnalise";
}

<h1>Pesquisa Visual Computacional</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovaAnalise" method="post" enctype="multipart/form-data">
            <div>
                <p>Busque sua imagem:</p>
                <p><input type="file" name="upload" accept="image/*" /></p>
                <p>Ou Informe a Url:</p>
                <p><input type="text" name="urlText" /></p>
                <p><input type="submit" value="Upload" class="btn btn-primary" /></p>
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <div>
            <h5>Imagem Carregada</h5>
            <img style="width: 80%; height: 80%;" src="@ViewBag.imageFile" />            
        </div>
    </div>
    <div class="col-md-4">
        <div>
            <h5>Análise da Imagem</h5>
            @Html.Raw("<pre style='white-space:pre-wrap;'>" + ViewBag.imageInfoStr + "</pre>")
        </div>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Views/CognitiveServices/ResultadoAnalise.cshtml
@model String

@{
    ViewData["Title"] = "ResultadoAnalise";
}

<h1>Resultado Analise</h1>

<div>
    <h4>Image Analysis</h4>
    <hr />
    @Html.Raw("<pre>" + ViewBag.imageInfo + "</pre>")
    <br>
    @*@<img src="ViewBag.imageFile" />*@
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GABCognitiveServices</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GABCognitiveServices</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CognitiveServices" asp-action="NovaAnalise">Nova Análise</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - GABCognitiveServices - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>